apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-multiarch-manifest
spec:
  tasks:
  - name: fetch-repository
    params:
    - name: url
      value: https://github.com/Basavaraju-G/multiarch-tekton-sample
    - name: deleteExisting
      value: "true"
    taskRef:
      kind: Task
      name: git-clone
    workspaces:
    - name: output
      workspace: myworkspace
  - name: build-amd64
    params:
    - name: IMAGE
      value: docker.io/basavaraju/tekton-image-amd64
    - name: IMAGE_PUSH_SECRET_NAME
      value: docker-image-push-secrets
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: myworkspace
  - name: build-s390x
    params:
    - name: IMAGE
      value: docker.io/basavaraju/tekton-image-s390x
    - name: IMAGE_PUSH_SECRET_NAME
      value: docker-image-push-secrets
    runAfter:
    - fetch-repository
    taskRef:
      kind: Task
      name: buildah
    workspaces:
    - name: source
      workspace: myworkspace
  - name: create-manifest
    params:
    - name: MANIFEST_NAME
      value: docker.io/basavaraju/tekton-image
    - name: IMAGE
      value: docker.io/basavaraju/tekton-image
    - name: IMAGE_PUSH_SECRET_NAME
      value: docker-image-push-secrets
    runAfter:
    - build-amd64
    - build-s390x
    taskRef:
      kind: Task
      name: buildah-manifest
    workspaces:
    - name: source
      workspace: myworkspace
  - name: check-image-manifest
    params:
    - name: buildahVersion
      value: latest
    - name: outputContainerImage
      value: docker.io/basavaraju/tekton-image
    runAfter:
    - create-manifest
    taskRef:
      kind: Task
      name: inspect-manifest
    workspaces:
    - name: source
      workspace: myworkspace
  workspaces:
  - name: myworkspace
